### ISSUE TITLE
Configure Evil-Sneak for F as in Clever-F?

### ISSUE THREAD

**Issue by ReneFroger** [hlissner/evil-snipe#1]
Thanks for sharing this plugin!

Although your plugin works for me, I would like to have same thing as Clever-F. 
I wonder if it's possible to emulate same behaviour as in [Clever-F](https://github.com/rhysd/clever-f.vim)?

**Comment by hlissner** [comment]
Not sure if you're still using this plugin, but native Clever-F style repeating has been implemented a while ago and evil-snipe-active-mode-map has been removed.

You can either replace evil-mode's native f/F/t/T/;/, functionality with evil snipe (which also enables evil-snipe repeating with s/S/f/F/t/T/;/,) like so:

`(evil-snipe-replace-evil) ;; replaces evil-mode's f/F/t/T/;/, with snipe`

Or just enable s/S repeating with:

`(evil-snipe-enable-sS)    ;; enable repeating with s/S`
