### ISSUE TITLE
Symbol groups?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#10]
It would be neat to be able to define that some symbols, i.e. the easy to reach `ø` (under the right pinky, dunno what it is in the US) could be redefined to mean a class of symbols, i.e. `(){}<>.;:_--`.

This way `saø` would match both `a. and` `a{`.

I do not know of this feature in any other `vim-sneak` alike, so it would put it ahead of the pack. Should probably not be too hard to implement either, must be doable with regexes and perhaps a macro.

**Comment by hlissner** [comment]
A fantastic idea. I'll need to refactor to implement it though, so this will have to wake until the weekend.
