### ISSUE TITLE
User-defined regexes?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#12]
This is slightly related to the idea of symbol groups #10 . Another idea might be to have a char for regexes, for example `æ`, the key to the left of the right pinky. Then the key coming after the `æ` would stand for a user defined regex.

I would use it like this: `sæf` to search with the regex (defined by me in a dotfile) `^def \w+):`.

This way I could quickly find all python function definitions with `sæfsss` (I always forget the function names). Another one could be `sæp` to find `@property`, etc.

I would probably create a different regex map for the different language modes.

This is probably more of a poweruser feature, but just throwing it out there. You could even have a crowd-configured library of useful regexes like yasnippet.

**Comment by hlissner** [comment]
Actually, this was exactly what I had planned to implement to solve #10. User-defined symbol groups. Additionally, each symbol group can be differently scoped.

For instance: `(add-to-list 'evil-snipe-symbol-groups '("[" "[{(" buffer))` would make searches for `sa[` jump to the next instance of `a[`, `a{` or `a(` anywhere in the entire buffer. The third parameter would be take anything that `evil-snipe-scope` accepts.

**Comment by hlissner** [comment]
And done. I haven't implemented symbol-group specific scopes, so right now it only takes character => regex pattern, like so:

`(add-to-list 'evil-snipe-symbol-groups '(?[ "[[{(]"))`

**Comment by halbtuerke** [comment]
Shouldn't this be?

```lisp
(add-to-list 'evil-snipe-symbol-groups '(?\[ "[[{(]"))
```

**Comment by hlissner** [comment]
Yes, it should. My mistake!



—Henrik

**Comment by halbtuerke** [comment]
Ok, then you might have to correct the docstring for `evil-snipe-symbol-groups`.

**Comment by endrebak** [comment]
The question mark means any of the preceding chars, so if you search with the command `sa[` it will replace it with a regex that matches `a [ or ( or {`. But will it work with `s[a`? Will try it out and see.

Thanks for implementing this, btw.

**Comment by endrebak** [comment]
How would you add the opposite, i.e. `]` matches `])}`? No regex I produce seem work (which isn't strange since `]` closes the regex brackets. I couldn't get escaping it to work either. Perhaps `(]|)|})`...

**Comment by halbtuerke** [comment]
> How would you add the opposite, i.e. ] matches ])}?

```lisp
(add-to-list 'evil-snipe-symbol-groups '(?\] "[]})]"))
```

**Comment by endrebak** [comment]
Brilliant, thanks.

**Comment by hlissner** [comment]
> Ok, then you might have to correct the docstring for evil-snipe-symbol-groups.

And done. Also, I've discovered a bug: symbol groups are ignored when repeating searches. I'm on that now.

**Comment by endrebak** [comment]
I'm now unable to repeat searches with `fFtT`. Anyone else have the same problem?

**Comment by hlissner** [comment]
At all? Just in case this is a MELPA issue, could you check out evil-snipe.el and tell me if you have 1.6.2 or 1.6.3?

**Comment by endrebak** [comment]
```
;; Version: 20150301.2131
;; X-Original-Version: 1.6.2
```
But this might be something wrong with the config on my end. When calling `M-x evil-snipe-override-mode` it works.

**Comment by hlissner** [comment]
Is `evil-snipe-override-evil` set to t?

**Comment by hlissner** [comment]
Oh, actually, you seem to be one version behind (the latest was 1.6.3, pushed ~15 minutes ago). I just bumped it to 1.6.4. I'm not sure how often MELPA checks for changes though.

**Comment by halbtuerke** [comment]
> I'm not sure how often MELPA checks for changes though.

In my experience MELPA updates every 10-30 minutes.

**Comment by endrebak** [comment]
Yes, that variable is set. Still not working, but that might be the setup on my side, so if no-one else has that problem please ignore.

Now using

```
;; Version: 20150302.49
;; X-Original-Version: 1.6.4
```

**Comment by endrebak** [comment]
This works for me now with the new version. Thanks.
