### ISSUE TITLE
Make evil-snipe-replace-evil a bool/var?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#13]
I created a pull request for an evil-snipe contribution layer in Spacemacs (their tagline should be "vim done right"): https://github.com/syl20bnr/spacemacs/pull/712

To make evil-snipe integrate better with Spacemacs, it would be nice if `(evil-snipe-replace-evil)` could be set/unset like a regular variable. Then replace-evil could be the default in the evil-snipe layer, but users would be able to turn it off in their `.spacemacs`-file.

If my talk of layers is confusing you, please see: https://github.com/syl20bnr/spacemacs#configuration-layers

**Comment by hlissner** [comment]
Can do. I'll let you know once I have.

**Comment by hlissner** [comment]
Alright, I've implemented the variable `evil-snipe-override-evil`. By default it's disabled.
