### ISSUE TITLE
evil-snipe--interactive: Symbol's value as variable is void: keys

### ISSUE THREAD

**Issue by halbtuerke** [hlissner/evil-snipe#14]
Hi,

I just upgraded evil-snipe via Melpa and every time I invoke it I get the following error message:

```lisp
evil-snipe--interactive: Symbol's value as variable is void: keys
```

I'm using `use-package` to configure my packages and have the following in my config

```lisp
            (use-package evil-snipe
              :ensure t
              :config (progn
                        (global-evil-snipe-mode 1)))))
```

I'm on GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C109)) of 2015-01-31

If you need more information just let me know.

**Comment by hlissner** [comment]
Whoops, I missed some lingering code. It should work properly now.

**Comment by halbtuerke** [comment]
Thanks for the quick fix. Now it works again.
