### ISSUE TITLE
Use snipe as a movement?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#15]
This might be a lot of work, but it would be nice to be able do something like `dsli` to delete until `li`.

**Comment by hlissner** [comment]
This already exists. In operator mode it uses `z/Z` instead of `s/S`, this is to preserve compatibility with evil-surround. `x/X` also exists as well (for exclusive motions).

**Comment by endrebak** [comment]
D'oh I'm heladum.
