### ISSUE TITLE
Better docs?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#16]
Would you be interested in a PR with an explanation of `evil-snipe`? I imagine that the images are kinda hard to understand, and that some visitors that aren't going to spend more than two secs to read the page and not understand anything and leave.

I feel that one of the first things on the page should be something like "what can evil-snipe do for me?", like I wrote for the spacemacs contrib layer: https://github.com/syl20bnr/spacemacs/tree/master/contrib/evil-snipe#description but more thorough.

**Comment by hlissner** [comment]
I agree, it needs work. I'll sit down one of these weekends and suss something out.

**Comment by hlissner** [comment]
Er, I forgot to reply about the PR: certainly, go ahead. I'll look it over as soon as I can.

**Comment by endrebak** [comment]
Feel free to look at the spacemacs contrib layer readme for inspiration:

https://github.com/syl20bnr/spacemacs/pull/754/files

**Comment by hlissner** [comment]
Just got around to this and could use a fresh pair of eyes on the new readme; what do you think?

The images have been taken down for now, I'm still figuring out a better way to do that.

**Comment by endrebak** [comment]
Sure; will do tonight.

**Comment by endrebak** [comment]
Emacs celeb endorsement: https://twitter.com/syl20bnr/status/610878194137305088

**Comment by hlissner** [comment]
Awesome!
