### ISSUE TITLE
Repeat `t/T` with `f/F`?

### ISSUE THREAD

**Issue by endrebak** [hlissner/evil-snipe#18]
`t/T` are more clunky to reach than `f/F` so it would be nice to be able to repeat `t/T` with `f/F`.

This could be an option, but why not just make it the default? If you are using `t<char>` followed by `f<char>` you are doing something wrong, so making `f/F` a special key after `t/T` should be safe.

**Comment by hlissner** [comment]
I didn't implement this directly (I believe it's an edge case), but I did refactor the repeat keymappings to public variables to make it easier for anyone to change the keymappings. Update evil-snipe and add this to your config:

```elisp
(define-key evil-snipe-mode-t-map "f" 'evil-snipe-repeat)
(define-key evil-snipe-mode-t-map "F" 'evil-snipe-repeat-reverse)
```

**Comment by endrebak** [comment]
Thanks, you are probably right that it is an edge case.
