### ISSUE TITLE
jump to next/prev match not working

### ISSUE THREAD

**Issue by wedens** [hlissner/evil-snipe#19]
I press s, type 2 chars, then pressing s/S/;/, and it's not working.
In `*Messages*` buffer:  `evil-snipe-repeat: Symbol's function definition is void: first`.

Related configuration:
```elisp
(require 'evil-snipe)
(global-evil-snipe-mode 1)
(setq evil-snipe-repeat-keys t)
(setq evil-snipe-scope 'visible)
(setq evil-snipe-repeat-scope 'whole-visible)
(setq evil-snipe-enable-highlight t)
(setq evil-snipe-enable-incremental-highlight t)

```

**Comment by wedens** [comment]
I found solution: `(require 'cl)`. I think evil-snipe should explicitly require this.

**Comment by hlissner** [comment]
I did one better and removed the depency on cl entirely. It should work fine now with or without the `(require 'cl)`.
