### ISSUE TITLE
[feature] Operating on incrementally extended regions

### ISSUE THREAD

**Issue by PythonNut** [hlissner/evil-snipe#22]
Okay, `evil-snipe` is super cool because it lets you think: _okay, I want to jump to that `z` over there, so <kbd>fz</kbd>. Oh, I'm not there yet? I'll just mash <kbd>f</kbd> until I am._ This is great because I have to worry less about those pesky letters that always seem to creep up between my point and target.

At the moment this doesn't extend to using motions as the ranges for an operator. <kbd>dfz</kbd> does work, of course, but if you missed that other `z` (the one sneaking between your point and your goal) then you're left having deleted less than you intended. This time, though, <kbd>f</kbd> won't save you. It'll search, but it won't extend the deletion.

I'm not entirely sure how to go around this. 

One simple way to solve this would be to simply `undo` the last operation and redo a new operation on the extended region, potentially in an invisible buffer so it doesn't jar the UI. The only caveat is that not all operations can be undone.

Another way would be to delay the operation until after the transient map terminates: <kbd>df</kbd> <kbd>f</kbd> <kbd>f</kbd> <kbd>f</kbd> <kbd>Up</kbd> \*now the deletion is done\*. Of course, this sort of violates the vim timing paradigm, so that's not a perfect solution either.

You _could_ just repeat the whole operation. That's pretty clean and side effect free, so long as you don't mind `("the cz" "the czechoslovakian food is amaz" "the czechoslovakian food is amazing z" ...)` in your `kill-ring`. (I wouldn't mind too much, but maybe other people would)

_A (hardly comprehensive) list of solutions to a problem that maybe doesn't even deserve solving_

What do you think?

**Comment by hlissner** [comment]
This would be nice for snipe's fluidity. Manipulating the kill-ring after the fact and repeating the whole operation should be doable, but I'll have to look into it. It'll involve capturing the operator and mimicking it. `evil-surround` does this, so I'll check out its implementation.

Note that you can currently do what you are asking with `evil-repeat` (<kbd>.</kbd>), but only in one direction. E.g. <kbd>dzcz</kbd> <kbd>.</kbd> <kbd>.</kbd>. I could simply remap transient map keys to `evil-repeat` for delete/change operations, but again, it'd only be in one direction. Unless I map the reverse key to an `evil-snipe-undo-maybe` sort-of-operation that undos up to the first operation.

Anyhow, I'm on the case!

**Comment by PythonNut** [comment]
> Note that you can currently do what you are asking with `evil-repeat` (<kbd>.</kbd>), but only in one direction. E.g. <kbd>dzcz</kbd> <kbd>.</kbd> <kbd>.</kbd>.

Not quite, because you can't then go and <kbd>p</kbd> the entire string... it's recorded in the `kill-ring` as separate pieces. You'd have to <kbd>pPPpPPpPP</kbd> to get the whole thing out in the right order again.

> Manipulating the kill-ring after the fact and repeating the whole operation should be doable, but I'll have to look into it.

I'm not sure how specific vs. general we need to be. If we focus on the `kill-ring`, we'll have an inconsistency because, <kbd>d</kbd> and, say, <kbd>=</kbd> don't behave the same (to say nothing of homegrown operators!).

> Anyhow, I'm on the case! 

Thanks!

**Comment by endrebak** [comment]
I have been meaning to post the same thing.

When you are doing this, you should look into repeat operations "leaking through" into insert mode (a teensy bug). 

Pressing `c t r` and then `t` (to type the letter `t` in insert mode) `evil-snipe` jumps to the next instance of `r` instead.

Note that something similar to this might be a feature, not a bug. If you meant to clear to `amaz`, but only got to `czechoslovakian` being able to press `t` again is a good thing. 

(But this leads to inconsistent behavior if you meant to type the letter `t`. You could add a timeout so that `t` means repeat clear until 0.2 seconds for example, but this is a tiny thing not worth bothering with unless you want to. I think `syl20bnr` implemented a timeout in `avy` which might be worth looking at.)

**Comment by endrebak** [comment]
This reminded me of another teensy annoyance; in `visual-mode` pressing `f/F` to repeat searches does not work.

**Comment by hlissner** [comment]
@endrebak I should have an immediate solution for the repeat operations leaking through from operator into insert mode. As for repeating searches with f/F in visual mode, this is something I already plan to address in evil-snipe 2.0.

Thanks for reporting! Though for future reference, please put these in separate issues. It helps me keep track of my TODO's.

**Comment by endrebak** [comment]
Understood and thanks.

**Comment by hlissner** [comment]
I think evil-easymotion fills this gap perfectly, so I'll consider this resolved.

**Comment by PythonNut** [comment]
@hlissner sure. Just wanted to throw this out there, in case we could come up with something. :)
