### ISSUE TITLE
clarification of evil-snipe-x intended exclusion behaviour

### ISSUE THREAD

**Issue by sooheon** [hlissner/evil-snipe#36]
|hello foo bar

If, given the above buffer, I were to type `dxfo`, I'm left with:

    |o bar

This seems to me like it's only half exclusive, and not quite what I expected. Should the exclusive motion rather give the following?

    |foo bar

**Comment by hlissner** [comment]
Good catch, this is indeed a bug! I'll look into it.

**Comment by hlissner** [comment]
And done. This was fixed in https://github.com/hlissner/evil-snipe/commit/688b645a3e52887bd87386597d95f423c355243f
