### ISSUE TITLE
Enhance snipe jumplist interaction

### ISSUE THREAD

**Issue by sooheon** [hlissner/evil-snipe#37]
from sneak.vim README:

> Press ctrl-o or \`\` to go back to the starting point.
> This is a built-in Vim motion; Sneak adds to Vim's jumplist only on s invocation—not repeats—so you can abandon a trail of ; or , by a single ctrl-o or ``.

Can we get this behaviour by leaving `:jump t` under `evil-snipe-def`, and setting `:jump nil` on `evil-snipe-repeat` and its reverse? After [this](https://github.com/PythonNut/evil-easymotion/issues/29#issuecomment-208182095) discussion, I realised that pushing to the jumplist after every small jump is not how vim does it by default either.

edit: maybe making this customisable would be better so those who prefer the current behaviour, or even no jumplist at all can have their way.

**Comment by hlissner** [comment]
Fixed! I thought the default vim-sneak behavior was best. The previous behavior can be done via snipe's repeating feature.
