### ISSUE TITLE
Wrongly highlights targets with letters reversed

### ISSUE THREAD

**Issue by sooheon** [hlissner/evil-snipe#38]
For example, if I snipe for `fi`, occurrences of `if` in buffer also get highlighted, though they do not get jumped to. 

Can be reproduced with (some may not be necessary):

```
(setq evil-snipe-scope 'buffer
        evil-snipe-repeat-scope 'buffer
        evil-snipe-enable-highlight t
        evil-snipe-enable-incremental-highlight t
        evil-snipe-auto-disable-substitute t
        evil-snipe-show-prompt t
        evil-snipe-smart-case t
        evil-snipe-repeat-keys nil)
```

**Comment by hlissner** [comment]
It wasn't cleaning up previous highlights (esp on failed snipes). That should fix it. Let me know if it persists.
