### ISSUE TITLE
Freezes in a large Org file

### ISSUE THREAD

**Issue by x-ji** [hlissner/evil-snipe#43]
`evil-snipe` works fine for me in normal code files/small Org files. However when I try to perform a `s/S` search in a very large Org file which contains over 10000 lines, Emacs simply freezes and I had to press `C-g` to get out of it.  Any idea what happened and how I might debug it? This is observed using [Spacemacs](https://github.com/syl20bnr/spacemacs) on Windows. I'm yet to test it on Ubuntu.
#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 64a0cc2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults spell-checking syntax-checking semantic chrome search-engine typography games restclient colors eyebrowse themes-megapack gtags vim-powerline evil-snipe unimpaired fsharp emacs-lisp haskell org markdown html yaml shell-scripts javascript c-c++)
```

**Comment by hlissner** [comment]
What is `evil-snipe-scope` set to? If it's set to `'buffer` (or worse, `'whole-buffer'), it tries to scan the rest of the document to highlight all matches. 

I know what to change to improve highlight performance, but in the meantime, you can fix this by setting it to `'visible` (only scans the visible portion of the buffer) or `'line` (only scans the current line), depending on your preference.

Let me know if that helps!

**Comment by hlissner** [comment]
To be more specific: `(setq evil-snipe-scope 'visible)` or `(setq evil-snipe-scope 'line)`

**Comment by x-ji** [comment]
Sorry, was occupied by something else and didn't try it out until today. Limiting the scope worked. Thanks.

**Comment by hlissner** [comment]
Now, highlighting will only focus on the visible window. This should resolve any performance concerns caused by scanning entire files. Feel free to reopen if that isn't the case.
