### ISSUE TITLE
evil-snipe-scope 'visible matches in non-visible parts

### ISSUE THREAD

**Issue by rcj** [hlissner/evil-snipe#51]
When setting `evil-snipe-scope` to `'visible` it will also match folded/invisible parts as long as they are part of the "visible" buffer. E.g. in org mode it will match in hidden sub-trees as long as the folded headline is in the visible part of the buffer. Is this intended?

**Comment by hlissner** [comment]
This is certainly unintended. Evil-snipe does no checks to see if a match is invisble/folded. The `'visible` scope just means it won't match beyond the bottom/top edges of the window.

I'll have a look at it over the weekend.

**Comment by hlissner** [comment]
Just pushed a fix addressing this. Please update and let me know if it resolves your problem.

**Comment by rcj** [comment]
Sorry for the late reply. Yes, it is now working as expected, thanks!
