### ISSUE TITLE
disabling evil-snipe-override-mode

### ISSUE THREAD

**Issue by CeleritasCelery** [hlissner/evil-snipe#53]
Thanks for evil-snipe!
if using `evil-snipe-override-mode` disabling hooks don't work. 

In particular the following code does NOT disable evil-snipe mode in ranger
```elisp
(evil-snipe-override-mode 1)
(add-hook 'ranger-mode-hook 'turn-off-evil-snipe-override-mode)
```
but using "normal" evil-snipe DOES
```elisp
(evil-snipe-mode 1)
(add-hook 'ranger-mode-hook 'turn-off-evil-snipe-mode)
```
evil snipe conflicts with several `ranger-mode` keybindings, particularly `;` which is bound to the `ranger-dired-map`. How do I disable `evil-snipe-override-mode` in ranger?

**Comment by hlissner** [comment]
You should be able to add `ranger-mode` to `evil-snipe-disabled-modes`:

```emacs-lisp
(push 'ranger-mode evil-snipe-disabled-modes)
```

To explain your particular problem: if you are using both `evil-snipe-mode` and `evil-snipe-override-mode`, you need to use **both** `turn-off-*` hooks to turn evil-snipe off completely:

```emacs-lisp
(evil-snipe-mode 1)
(evil-snipe-override-mode 1)
(add-hook 'ranger-mode-hook 'turn-off-evil-snipe-mode)
(add-hook 'ranger-mode-hook 'turn-off-evil-snipe-override-mode)
```

I realize that's kind of bulky though, so `evil-snipe-disabled-mode` is the better option.

**Comment by CeleritasCelery** [comment]
Thank you. I am not sure if it is problem with ranger of with evil-snipe, but adding ranger-mode to `evil-snipe-disabled-modes` does not disable `evil-snipe-override-mode`.

Here is my minimal config with stock Emacs
```elisp
(evil-mode 1)
(setq evil-snipe-disabled-modes '(ranger-mode))
(add-hook 'ranger-mode-hook 'turn-off-evil-snipe-override-mode)
(evil-snipe-override-mode 1)
```
then open ranger and see that `evil-snipe-override-mode` is still enabled. 

As I mentioned above this doesn't happen with `evil-snipe-mode`, only `evil-snipe-override-mode`.

**Comment by CeleritasCelery** [comment]
Turns out that you need add both `turn-off-evil-snipe-override-mode` **AND** `turn-off-evil-snipe-mode` to the ranger hook to get it to work correctly.
