### ISSUE TITLE
update keymap name in readme

### ISSUE THREAD

**Issue by JJPandari** [hlissner/evil-snipe#55]
I've just updated to the latest version on melpa/github, and found my configs using `evil-snipe-mode-map` no longer works. After taking a look at the source code I changed the name to `evil-snipe-local-mode-map` and everything worked fine again. But it confused me for a few minutes.  

It would be nice for you to change the name in readme in case a new user come to read it.

**Comment by hlissner** [comment]
Sorry for the terribly long delay. This has no been fixed. Thanks for letting me know!
