### ISSUE TITLE
Keep current snipe when can't find further chars

### ISSUE THREAD

**Issue by JosephFerano** [hlissner/evil-snipe#56]
Currently I'm using evil-snipe a la Clever-F, and it works as intended. The only thing I noticed is that if I land on the last occurrence and hit 'f' again while on it, I'll get a message saying "Can't find _char_" and I'll lose the current snipe and I'll have to reinput the snipe again, in the reverse direction. Is there anyway to change this behavior? If you need clarification, I can give examples.

**Comment by hlissner** [comment]
Sorry that I've only gotten to this now. This should be fixed as of 3ae382d, so I'll consider this resolved. Feel free to reopen this if that isn't the case.
