### ISSUE TITLE
evil-snipe-override doesn't work when first pressing f/F/t/T

### ISSUE THREAD

**Issue by yunhao94** [hlissner/evil-snipe#66]
# Environment
- Arch Linux
- GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30
# Reproduction steps
1. `emacs -Q`
2. `M-x package-initialize`
3. `M-x evil-mode`
4. `M-x evil-snipe-override-mode`
5. `C-h k f`
# Expected behavior
evil-snipe-f
# Actual behavior
evil-find-char

**Comment by hlissner** [comment]
This a more generally limitation of evil keymaps. Adding `(evil-normalize-keymaps)` to the end of your repro steps fixes the issue. It is necessary to call this command whenever a new minor mode keymap (with evil state keybinds) is defined, unfortunately.

I'll switch out `evil-define-key*` for `evil-define-minor-mode-key` (which was written to address this issue, iirc) and see if it addresses the problem well enough.

**Comment by hlissner** [comment]
Sorry for the tremendously late reply. 1f3ba0d should fix this issue.
