### ISSUE TITLE
Search in both directions

### ISSUE THREAD

**Issue by linwaytin** [hlissner/evil-snipe#68]
This is a very useful plugin, but I meet a problem.

Sometimes I want to jump to, say, 'wo' before the current position of cursor.
I press `s` and expect I can use `S` to jump backward to.
However, if there is no 'wo' after the current position of my cursor,
then I get "can' find 'wo'".

This is a little bothering because I need to take care of the relative position between the cursor and the position I want to jump to in my mind.
Is there a way to solve this issue?

Thanks for such a good work.

**Comment by hlissner** [comment]
You can press `;` and `,` to repeat the last search forward or backward. Press `,` after a failed search.

Otherwise, https://github.com/PythonNut/evil-easymotion might be what you want.

**Comment by linwaytin** [comment]
Thank you. That works.
I think this plugin is mentally easier than easymotion for me. Great job.
