### ISSUE TITLE
t movement broken (inconsistent with vim and/or vanilla evil)

### ISSUE THREAD

**Issue by leoalekseyev** [hlissner/evil-snipe#70]
**Example**
Here is a sample line from doom emacs config:
```
       company           ; the ultimate code completion backend
```
Consider the point being anywhere inside the word "company" and issue the command `vt<SPC>`.

**What did you expect to happen?**
Visual mark extends from where the point was to the end of the word (up until the first space)

**What actually happened?**
```
       company           ; the ultimate code completion backend
                      ^-------- visual mark extends to here
```

**Discussion**
It can be worked around with (setq evil-snipe-skip-leading-whitespace nil) for the time being. The issue is evil-snipe isn't recognizing that continuous stream of whitespace as non-indentation.

**Comment by hlissner** [comment]
As of 6dcac7f `evil-snipe-skip-leading-whitespace` should work as expected. That is, it should only skip _leading_ whitespace, and not skip over non-whitespace to get to the whitespace to be skipped over. Thanks for bringing it to my attention!
