### ISSUE TITLE
Evil snipe in the minibuffer?

### ISSUE THREAD

**Issue by galagora** [hlissner/evil-snipe#73]
It would be super useful if this worked while in normal state in the minibuffer. Does allowing it cause any issues?

**Comment by hlissner** [comment]
Unfortunately this has nothing to do with evil-snipe itself. You'd have to find a way to enable evil mode _in_ the minibuffer. Check out [evil-collection, which has managed to do that](https://github.com/emacs-evil/evil-collection) by setting `evil-collection-setup-minibuffer` to `t`.

**Comment by galagora** [comment]
I already got Evil to work in the minibuffer (by binding `C-<escape>` to `evil-normal-mode` in the global map, so I don't have to press escape twice to leave). The problem appears to be that [snipe specifically checks if it's in the minibuffer](https://github.com/hlissner/evil-snipe/blob/master/evil-snipe.el#L600). Should be a quick fix, I just thought that not doing the check had previously caused issues. It's fairly easy to work around, though so it's not a huge deal:
```emacs
(map! :g "C-<escape>" (cmd! (progn (evil-normal-state)
                                   (evil-snipe-local-mode +1)
                                   (evil-snipe-override-local-mode +1))))
```
