### ISSUE TITLE
Error: Symbol's Value as variable is void: count

### ISSUE THREAD

**Issue by nazzacode** [hlissner/evil-snipe#76]
Hey, beginners question here, 

I have doom emacs which comes with inbuilt snipe functionality, but when I try to use any of the snipe functions I get the following error:

"Symbol's Value as variable is void: count"

does anyone know what could be going on?

**Comment by hlissner** [comment]
An error is occurring. There is little else I can glean from that without a backtrace. Please [produce a backtrace from the error](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).
