### ISSUE TITLE
invalid-function when calling `evil-snipe-...`

### ISSUE THREAD

**Issue by d1egoaz** [hlissner/evil-snipe#91]
### What did you expect to happen?

It was working without any issues, I wonder if other package or a recent emacs version broke it 

## `evil-snipe-f`:
```
Debugger entered--Lisp error: (invalid-function 1)
  1(0 1)
  evil-snipe--collect-keys(nil t)
  (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction))
  (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction)))
  (let ((count (if current-prefix-arg (prefix-numeric-value current-prefix-arg)))) (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction))))
  command-execute(evil-snipe-f)
```

## `evil-snipe-s`:
```
Debugger entered--Lisp error: (invalid-function 2)
  2(0 2)
  evil-snipe--collect-keys(nil t)
  (let ((evil-snipe--match-count 2)) (evil-snipe--collect-keys count evil-snipe--last-direction))
  (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 2)) (evil-snipe--collect-keys count evil-snipe--last-direction)))
  (let ((count (if current-prefix-arg (prefix-numeric-value current-prefix-arg)))) (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 2)) (evil-snipe--collect-keys count evil-snipe--last-direction))))
  command-execute(evil-snipe-s)
```

### Steps to reproduce

1. Install package
2. Use mentioned functions

```elisp
;;** evil-snipe.el
(use-package evil-snipe
  :after evil
  :general
  (general-nmap :keymaps 'evil-snipe-local-mode-map
    "s" 'evil-snipe-s
    "S" 'evil-snipe-S)
  :config
  (setq evil-snipe-scope 'line)
  (setq evil-snipe-smart-case t)
  (evil-snipe-mode 1)
  (evil-snipe-override-mode 1)
  :hook ((magit-mode-hook . turn-off-evil-snipe-override-mode)
         (after-init-hook . evil-snipe-mode)))
```

### Package commit

c07788c35cf8cd8e652a494322fdc0643e30a89f

### System Information

GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-03-23

**Comment by kpot** [comment]
Same problem on my machine. Keep getting `evil-snipe--collect-keys: Invalid function` every time I press "f", even with pristine clean `config.el` file. Sorry, don't have enough experience with ELisp at the moment to learn more.

## System information

GNU Emacs 29.0.60 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2202.70 Version 11.7.2 (Build 20G1020)) of 2023-03-25
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD 4e105a95 2023-03-22 18:29:38 -0400
Doom modules  v23.03.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD 4e105a95 2023-03-22 18:29:38 -0400

## Temporary workaround

Had to temporarily disable evil-snipe with
```
(package! evil-snipe :disable t)
```
added to `~/.doom.d/packages.el`. To make at least the standard "f" search work.

**Comment by JosephFerano** [comment]
I recently tried updating my init.el and switched some things around like using elpaca instead of straight.el. Since then, it broke, and I am getting the same error

```lisp
Debugger entered--Lisp error: (invalid-function 1)
  1(0 1)
  evil-snipe--collect-keys(nil t)
  (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction))
  (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction)))
  (let ((count (if current-prefix-arg (prefix-numeric-value current-prefix-arg)))) (list (progn (setq evil-snipe--last-direction t) count) (let ((evil-snipe--match-count 1)) (evil-snipe--collect-keys count evil-snipe--last-direction))))
  command-execute(evil-snipe-f)
```

**Comment by vlaci** [comment]
Maybe a compilation issue? If I open the definition of `evil-snipe--collect-keys`, `M-x eval-defun` on it, the problem goes away. `evil-escape` has a very similar issue too.

**Comment by d1egoaz** [comment]
The issue was related to a bug in a recent emacs 29/30.

https://www.reddit.com/r/emacs/comments/121xnak/emacs_29_broken_packages_since_last_update/

After reverting to a previous version, everything started working again.

And it looks there is now a new commit in 30 that also fixes the issue.
